################################################################################
# ----- LLIBRERIES EMPRADES EN EL PROJECTE -----
################################################################################

library(data.table)
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(tibble)
library(ggplot2)
library(lattice)
library(stringr)
library(psych)
library(lattice)
library(scales)
library(patchwork)
library(gplots)
library(car)
library(MASS)
library(lme4)
library(lmerTest)
library(kableExtra)
library(gtsummary)
library(FactoMineR)
library(factoextra)
library(sf)
library(here)
library(leaflet)
library(htmltools)
<<<<<<< HEAD
library(knitr)
=======
library(randomForest)
library(xgboost)
library(rsample)
library(fastshap)
library(vip)
library(caret)
>>>>>>> 336111ee836f754c9b51734679637016098ace54
