---
title: "Descripció de les variables"
author: "Segon Salmerón Èric (1672984)"
date: "2026-01-07"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

La nostra base de dades final compte amb les següents 37 variables:


\begin{enumerate}
  \item \textbf{candidatura} Identificador de la candidatura electoral.
  \item \textbf{proces} Tipus de procés electoral (En aquest cas només hi ha eleccions generals codificades amb 02).
  \item \textbf{any} Any electoral (2015, 2016, 2019 o 2023).
  \item \textbf{mes} Mes en què se celebra l’elecció.
  \item \textbf{volta} Mes? (pren el mateix valor que la variable mes)
  \item \textbf{ccaa} Comunitat autònoma de la secció censal (En aquest cas sempre és Catalunya, codificada amb 09).
  \item \textbf{provincia} Codi de província corresponent a la secció censal.
  \item \textbf{municipi} Codi del municipi.
  \item \textbf{districte} Codi del districte electoral.
  \item \textbf{seccio} Codi de la secció censal.
  \item \textbf{tipus} Tipus de candidatura o agrupació electoral (partit polític, coalició, agrupació d’electors o altres formes jurídiques).
  \item \textbf{vots} Nombre total de vots obtinguts per la candidatura a la secció censal.
  \item \textbf{sigles} Sigles del partit o candidatura.
  \item \textbf{nom\_partit} Nom del partit o candidatura.
  \item \textbf{Municipi} Nom del municipi.
  \item \textbf{Codi\_municipi} Codi del municipi.
  \item \textbf{Districte} Codidel districte.
  \item \textbf{Edad media de la población} Edat mitjana de la població resident a la secció censal.
  \item \textbf{Población} Nombre total d’habitants de la secció censal.
  \item \textbf{Porcentaje de hogares unipersonales} Percentatge de llars formades per una sola persona.
  \item \textbf{Porcentaje de población de 65 y más años} Percentatge de població amb 65 anys o més.
  \item \textbf{Porcentaje de población española} Percentatge de població amb nacionalitat espanyola.
  \item \textbf{Porcentaje de población menor de 18 años} Percentatge de població menor de 18 anys.
  \item \textbf{Tamaño medio del hogar} Nombre mitjà de persones per llar.
  \item \textbf{Distribución de la renta P80/P20} Ràtio entre el percentil 80 i el percentil 20 de la renda.
  \item \textbf{Índice de Gini} Índex de desigualtat de la renda.
  \item \textbf{Fuente de ingreso: otras prestaciones} Percentatge de llars amb ingressos provinents d’altres prestacions socials.
  \item \textbf{Fuente de ingreso: otros ingresos} Percentatge de llars amb ingressos procedents d’altres fonts no especificades.
  \item \textbf{Fuente de ingreso: pensiones} Percentatge de llars amb ingressos provinents de pensions.
  \item \textbf{Fuente de ingreso: prestaciones por desempleo} Percentatge de llars amb ingressos provinents de prestacions d’atur.
  \item \textbf{Fuente de ingreso: salario} Percentatge de llars amb ingressos principals procedents del salari.
  \item \textbf{Media de la renta por unidad de consumo} Renda mitjana per unitat de consum a la secció censal.
  \item \textbf{Mediana de la renta por unidad de consumo} Mediana de la renda per unitat de consum.
  \item \textbf{Renta bruta media por hogar} Renda bruta mitjana per llar.
  \item \textbf{Renta bruta media por persona} Renda bruta mitjana per persona.
  \item \textbf{Renta neta media por hogar} Renda neta mitjana per llar.
  \item \textbf{Renta neta media por persona} Renda neta mitjana mitjana per persona.
\end{enumerate}


