---
title: "Importacio"
author: "Jordi Anguera"
date: "2025-12-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importació de dades

```{r}
library(data.table)
library(dplyr)

lines <- readLines("10022307.DAT")

df <- data.frame(
  proces      = substr(lines, 1, 2),
  any         = substr(lines, 3, 6),
  mes         = substr(lines, 7, 8),
  ccaa        = substr(lines, 9, 10),
  provincia   = substr(lines, 11, 12),
  municipi    = substr(lines, 13, 15),
  districte   = substr(lines, 16, 18),
  seccio      = substr(lines, 19, 21),
  tipus       = substr(lines, 23, 23),
  candidatura = substr(lines, 24, 29),
  vots        = as.integer(substr(lines, 30, 36)),
  stringsAsFactors = FALSE
)

head(df)
dim(df)
str(df)
summary(df$vots)

sum(df$vots, na.rm = TRUE)

n_mesas <- length(unique(
  paste(df$provincia, df$municipi, df$districte, df$seccio, df$mesa)
))

n_seccions <- length(unique(
  paste(df$provincia, df$municipi, df$districte, df$seccio)
))

c(mesas = n_mesas, seccions = n_seccions)

df$codi <- paste0(
  sprintf("%02s", df$provincia),
  sprintf("%03s", df$municipi),
  sprintf("%02s", df$districte),
  sprintf("%03s", df$seccio)
)

```

